### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by MPSforca** [almeidadelucas/justice-for-all#1]
Para o desenvolvimento do Login será preciso desenvolver a tela do Front-End e o Endpoint de Login no Backend, que consultará a tabela de Usuários para confirmar as credenciais.

**Tela de Login**
A tela de Login deverá ser composta por campos de email e senha, e um botão para enviar a requisição. A requisição deve ser enviada por um header Authorization (Basic Auth)

**Endpoint de Login**
O endpoint deverá ser um `POST /login`, que interpretará o header Authorization e consultará o Banco de Dados para saber se as credenciais estão corretas.
- Status 204, caso seja sucesso
- Status 401, caso o token com as informações de cadastro seja inválido
- Status 500, caso qualquer outro erro aconteça

**Status do Desenvolvimento**
- [x] Tela de Login
- [x] Endpoint de Login

**Comment by almeidadelucas** [comment]
Iniciando o desenvolvimento da tela de login, sem chamadas para o backend

**Comment by MPSforca** [comment]
Vou começar a fazer o Endpoint no Backend
