### ISSUE TITLE
Cadastro de Usuário

### ISSUE THREAD

**Issue by MPSforca** [almeidadelucas/justice-for-all#3]
Desenvolvimento da tela de cadastro e dos serviços Back-end que serão consumidos nessa Feature.

**Tela Front-End**
Na tela de cadastro, será preciso coletar as informações básicas do usuário:
- Nome Completo
- E-mail
- Senha (que deverá ser armazenada criptografada no banco de dados)
- O tipo de usuário que está sendo cadastrado: Advogado ou Pessoa Física
- CPF (caso seja pessoa física) ou número da OAB (se for advogado)

**Banco de Dados**
Também é preciso criar uma tabela no banco de dados para armazenar os usuários com as seguintes colunas:
- FIRST_NAME
- LAST_NAME
- EMAIL
- PASSWORD
- TYPE (0 = Admin, 1 = Advogado, 2 = Pessoa Física)
- CPF
- OAB

**Back-End**
Já para o endpoint do serviço de Backend, deveremos criar um `POST /user`, no qual deveremos receber no Payload as informações do cadastro:
```json
{
    "firstName":  "First Name",
    "lastName":  "Last Name",
    "email":  "email@email.com",
    "password":  "password",
    "type":  "LAWYER | CLIENT",
    "cpf":  "3281236412",
    "oab":  "123456"
}
```
Os retornos serão:
- HTTP 201, no caso de sucesso
- HTTP 422, caso algum campo esteja com formato inválido
- HTTP 500, no caso dos demais erros

Status do Desenvolvimento:
- [x] Desenvolvimento da tela de Cadastro
- [x] Criação de um _endpoint_ no Backend para realizar o cadastro de usuários
- [x] Criação da tabela de Usuário no banco de dados

**Comment by MPSforca** [comment]
Vou comecar a trabalhar na parte do Banco de Dados e do Back-End dessa Issue

**Comment by MPSforca** [comment]
As validações que fazemos no Backend para cada campo:
Todos os campos são obrigatórios (com exceção de OAB e CPF que dependem da categoria)
- OAB é obrigatório para Advogado
- CPF é obrigatório para Cliente

Validações extras:
- EMAIL: Checamos se bate com um formato padrão de email
- CPF: Se tem 11 dígitos e todos são numéricos
- Primeiro Nome: Se tem entre 2 e 30 caracteres
- Último Nome: Se tem entre 2 e 100 caracteres
- OAB: Se os dois primeiros dígitos são letras A-Z e se os 6 outros dígitos são números
- Senha: Se tem mais de 8 caracteres

**Comment by almeidadelucas** [comment]
Iniciando o desenvolvimento do frontend
