### ISSUE TITLE
Corrigir Code Smells

### ISSUE THREAD

**Issue by MPSforca** [almeidadelucas/justice-for-all#32]
Corrigir os seguintes Code Smells encontrados durante análise do projeto:

### 1 - Comentários
Há alguns comentários na classe `CPFValidator.java` (linhas 24 a 35) do projeto Backend que podem ser removidos uma vez que representam o Code Smell [Comments](https://refactoring.guru/smells/comments)  do tipo **Dispensables**, conforme demonstrado no trecho a seguir:
```
int[] digitosCopiados = Arrays.copyOf(digitosOriginais, digitosOriginais.length);
/////primeiro digito
int digito0 = digitoEsperado(digitosOriginais, 0);
digitosCopiados[9] = digito0;
/////segundo digito
int digito1 = digitoEsperado(digitosCopiados, 1);
digitosCopiados[10] = digito1;
//////validação
if (digitosOriginais[9] != digito0 || digitosOriginais[10] != digito1) {
    throw new InvalidUserFieldException("The CPF is not properly formatted");
}
```
Julga-se que seja possível aplicar um tratamento de modo que parte do código seja extraído para uma função ou que variáveis sejam renomeadas ou introduzidas para que assim o código fique intuitivo o suficiente para não necessitar de comentários.

### 2 - Método Longo
Na classe `SignupForm.tsx` do projeto Front-End, há o metodo chamado `validate()` que está bem longo, com cerca de 35 linhas de código. Isso representa um Code Smell [Long Method](https://refactoring.guru/smells/long-method) do tipo **Bloaters**:
```
const validate = () => {
		...

		if (!formValues.email.match(EMAIL_REGEX)) {
			newErrors.email = 'Email deve seguir o formato "email@email.com"';
		}
		if (formValues.firstName.length < 2 || formValues.firstName.length > 30) {
			newErrors.firstName = 'O primeiro nome deve conter mais que duas letras e menos de 30';
		}
		if (formValues.lastName.length < 2 || formValues.lastName.length > 100) {
			newErrors.lastName = 'O sobrenome nome deve conter mais que duas letras e menos de 100';
		} 
		if (formValues.cpf && formValues.cpf?.length !== 11) {
			newErrors.cpf = 'CPF deve conter 11 dígitos';
		}
               ...
```
Como o crescimento do projeto pode tornar essa função mais difícil ainda de dar manutenção, acredita-se que uma refatoração seja bem-vinda nesse método para torná-lo mais legível e expandível no futuro para novas adições de validação.

### 3 - Feature Envy entre CreateUserCommand e CreateUserValidator
Atualmente, temos uma classe que chama `CreateUserValidator` que basicamente olha pra todos os campos da classe `CreateUserCommand` através do pattern _Chain of Responsability_ e faz a validação de cada um destes.
O problema é que isso pode representar um Code Smell [Feature Envy](https://refactoring.guru/smells/feature-envy) do tipo **Couplers**.
Dessa forma, a classe `CreateUserValidator` fica totalmente acoplada à classe `CreateUserCommand` a nível de que, qualquer alteração nos campos de criação de usuário nos forcem a alterar ambas as classes (uma para modificar o campo e outra para modificar a validação desse campo).

### 4 - Large Class
Atualmente, a classe `CaseServiceImpl` possui muitos métodos, tornando essa classe responsável pela lógica de criar um caso, filtrar casos e recuperar casos por parâmetros diferentes. 
Essa responsabilidade concentrada na classe representa um Code Smell [Large Class](https://refactoring.guru/smells/large-class) do tipo **Bloaters**.
Dessa forma, a classe `CaseServiceImpl` concentra muita lógica que poderia estar separada em outras classes. Da forma como está feito agora fica difícil de trabalhar no código pois os desenvolvedores precisam ler muito código até encontrar a parte que desejam modificar. 

## Status de Desenvolvimento
- [x] 1 - Comentários do `CPFValidator`
- [x] 2 - Método Longo no `SignupForm.tsx`
- [x] 3 - Feature Envy entre `CreateUserCommand` e `CreateUserValidator`
- [x] 4 -  Large Class `CaseServiceImpl`

**Comment by MPSforca** [comment]
Pessoal, vou fazer o Code Smell 3 (Feature Envy entre CreateUserCommand e CreateUserValidator)

**Comment by almeidadelucas** [comment]
Pessoal, peguei o Code Smell 2 para fazer

**Comment by JonathanDoOuro** [comment]
Finalizei a correção do Code Smell 1 e o 4.

**Comment by almeidadelucas** [comment]
O code smell 2 foi resolvido criando hooks individuais para validação de cada campo do formulário. Utilizamos tb uma lib para facilitar nas validações
